### ISSUE TITLE
uncaught TypeError: t._pc.addTrack is not a function

### ISSUE THREAD

**Issue by teeramusic** [feross/simple-peer#153]
It was working fine with Adapter.js, but since I updated to the latest version of Simplepeer, now I get this error. 

```javascript
 uncaught TypeError: t._pc.addTrack is not a function
    at https://localhost/js/simplepeer.min.js:3:2861
    at Array.forEach (native)
    at new u (https://localhost/js/simplepeer.min.js:3:2835)
```

**Comment by RationalCoding** [comment]
What browser are you getting this in?

**Comment by teeramusic** [comment]
Oh sorry, Chrome. Works in firefox.

**Comment by RationalCoding** [comment]
That's strange. Chrome doesn't have support for tracks, so that line shouldn't be running.

Could you check your version of simple-peer and Chrome?

**Comment by RationalCoding** [comment]
Also, let me know if this pen runs for you.
https://codepen.io/RationalCoding/pen/JWPeXZ?editors=1111

**Comment by teeramusic** [comment]
Chrome 56.0.2924.87
simple-peer 6.4.3

**Comment by teeramusic** [comment]
I got the alert "worked"
and in the log got stream

**Comment by teeramusic** [comment]
If I remove Adapter.js, simple-peer works on chrome again, but then broken in other browsers (such as edge)

**Comment by RationalCoding** [comment]
OK, so I think adapterjs is adding the `ontrack` event to Chrome but not the `addTrack` method, so the way simple-peer is checking for track support isn't working

I'll change it so that we are checking for 'addTrack` instead.

Also consider opening an issue on adapter.js so that they properly shim track support (if that's even possible), or remove the ontrack event from Chrome.

Here's the new build with the fix: https://raw.githubusercontent.com/RationalCoding/simple-peer/temp-build/simplepeer.min.js

**Comment by teeramusic** [comment]
Amazing! Thank you for the awesome work!

**Comment by feross** [comment]
@RationalCoding We usually keep issues open until the relevant fix is merged on `master`, since it makes it easier to track what's actually been fixed and what is waiting for a PR. No worries this time. Thanks for the debugging work!
