### ISSUE TITLE
DOMException: Failed to execute 'send' on 'RTCDataChannel': Could not send data

### ISSUE THREAD

**Issue by RationalCoding** [feross/simple-peer#170]
Exception thrown when trying to `peer.send()` large amounts of data very quickly.

I think this is to do with the datachannel limiting. Unfortunately the channel closes right after, so we can't just retry later.

Should we buffer data when we can't send it? Or is there a better way to do this outside of simple-peer?

**Comment by RationalCoding** [comment]
I saw you hit this issue on instant.io @feross. Was wrapping it in a try/catch and doing the buffering yourself the correct solution?

**Comment by RationalCoding** [comment]
Is there some kind of property on the datachannel that we can expose to know if it's ready to send?

**Comment by feross** [comment]
`peer.send()` just calls the underlying `datachannel.send()` method. It is very low-level and doesn't check to see that sending will work.

If you use `peer.write()` or pipe to the stream instead, you shouldn't have any issues. Note that we get `peer.write()` because we inherit from the `stream.Duplex` class.

You can see how we handle backpressure here: https://github.com/feross/simple-peer/blob/00d6b40f3758ffe26551bfae6fa18a9b17edf01f/index.js#L361 but that property is not exposed.

**Comment by feross** [comment]
FWIW, Firefox is about to ship an improvement that allows you to call `peer.send()` with data up to 1GB (!!) More info here: https://bugzilla.mozilla.org/show_bug.cgi?id=979417
