### ISSUE TITLE
Error while sending Blob in Chrome and Chromium

### ISSUE THREAD

**Issue by tenisaltos** [feross/simple-peer#218]
I am trying to send a Blob file (a video file in this case) over the data channel and get the following error on the sender's client ...

Unhandled Promise rejection: Failed to execute 'send' on 'RTCDataChannel': Blob support not implemented yet ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'send' on 'RTCDataChannel': Blob support not implemented yet
    at f.send (https://cdnjs.cloudflare.com/ajax/libs/simple-peer/6.2.1/simplepeer.min.js:3:5523)

... This feature works in both Windows and Linux versions of Firefox.

Thank you very much for such a an easy to use API.

**Comment by RationalCoding** [comment]
The problem is exactly what the error says, Blob objects can't be sent over data channels. You need to convert it to a binary buffer and then rebuild the blob on the receiving peer.

Blob to buffer: https://github.com/feross/blob-to-buffer
Buffer to blob: https://www.npmjs.com/package/buffer

You'll end up with something like this:
```javascript
toBuffer(blob, function (err, buffer) {
  if (err) throw err

  peer.push(buffer)
  peer.push(null);
})
```

```javascript
var partialBuffers = []
peer.on('data', (data) => partialBuffers.push(data))
peer.on('end', () => {
   var receivedBlob = new Blob(partialBuffers)
}
```

Note this closes the connection after sending just 1 blob. There's likely a convenient module floating around.
