### ISSUE TITLE
Incompatibility with Angular 6+

### ISSUE THREAD

**Issue by omardoma** [feross/simple-peer#318]
simple-peer doesn't work with the latest Angular 6

<img width="344" alt="screen shot 2018-06-01 at 3 20 22 pm" src="https://user-images.githubusercontent.com/25301162/40842834-679b62be-65af-11e8-8a45-84e601ad5e04.png">

Seems to be related that the Angular team removed support (shim) of process and global variables in browser.

The angular issue: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by nazar-pc** [comment]
Simple-peer doesn't contain anything Angular-specific, it is standalone library that works everywhere.
Since simple-peer works with everything except Angular 6, this is Angular's tooling issue and its developers need to fix their stuff.

Also you can use `simplepeer.min.js` in browser that includes everything necessary for simple-peer to function.

Because of said above I'm closing this issue. Feel free to continue conversation if you believe there is a bug in simple-peer that needs to be fixed.
