### ISSUE TITLE
turn server support

### ISSUE THREAD

**Issue by panjwanihp** [feross/simple-peer#320]
can i make an web app in angular 4 using simple peer such that more than two people can do video chat and does it support turn servers. is any example available  in angular 4 using simple peer ?

**Comment by nazar-pc** [comment]
Yes, you definitely can. There is nothing Angular-specific in simple-peer, so if you know how to use Angular - you'll be able to use simple-peer with it, otherwise you'll need to learn a bit of Angular first.

As for Turn servers, you can specify them via `config.iceServers` option similarly to Stun servers.
