### ISSUE TITLE
Remove "legacy" WebRTC API

### ISSUE THREAD

**Issue by t-mullen** [feross/simple-peer#336]
Apple has disabled the callback version of most WebRTC methods. This is what is causing the Safari 11 tests to fail.

They can be made to pass by enabling `Develop > WebRTC > Enable Legacy WebRTC API` in Travis, or by replacing the legacy API in simple-peer.

**Comment by RationalCoding** [comment]
Oddly enough, Chrome displays the same "transceiver's are required" behaviour for constraints as Safari when the promise API is used (the callback version works as expected). https://bugs.webkit.org/show_bug.cgi?id=186576

**Comment by fippo** [comment]
@RationalCoding how does the callback version differ from the promise one? Note that createOffer does not create state unless you call setLocalDescription

**Comment by RationalCoding** [comment]
The Promise version in Chrome doesn’t update constraints on renegotiation. My guess is that it wasn’t implemented since these constraints are deprecated in favour of transceivers (which is why they aren’t supported in the Safari Promise API either). When transceivers have good support, we can switch to that and use promises everywhere.

Safari no longer supports the callback API by default, so this change is required to support it.

**Comment by vblagomir** [comment]
Even with the latest commit "feross/simple-peer#90c14a8d9df1986ec1c751312e478fb70e122638" I still have the `Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary` error in Safari Technology Preview 65.

**Comment by vblagomir** [comment]
I have initially installed it wrongly, after reinstal the `feross/simple-peer#90c14a8d9df1986ec1c751312e478fb70e122638` works fine in the Safari Technology Preview 65. 👍

**Comment by t-mullen** [comment]
This work is done.
