### ISSUE TITLE
New version release to npm?

### ISSUE THREAD

**Issue by saranrapjs** [feross/simple-peer#365]
Hi! I'm excited to see all of the work that's been done to support the promise-style WebRTC method signatures, which will allow simple-peer to work on Safari. It looks like, though, no new version has been released to npm since then. Would it be possible to release a new version including all of these recent commits?

**Comment by chrisprobst** [comment]
Also very interested in this new release!

**Comment by jadbox** [comment]
@feross Post 21 days, please advice. Do you need more maintainers?

**Comment by mrlika** [comment]
Hi,

I am a developer of [P2P Media Loader](https://github.com/Novage/p2p-media-loader). It uses [WebTorrent tracker client](https://github.com/webtorrent/bittorrent-tracker) library to do WebRTC signaling using public WebTorrent trackers. It eliminates the need in server-side software and enables easy zero cost setup of live P2P video streaming.

But it doesn't work with macOS Safari only because WebTorrent client uses simple-peer library :-(

How can we help with this release?

**Comment by t-mullen** [comment]
9.2.0 is published!
