### ISSUE TITLE
initiator peers are always connected:false for non initiators

### ISSUE THREAD

**Issue by NikosEfthias** [feross/simple-peer#373]
i have similar set up to the ones in your examples
```js
const p1=new Peer({initiator:true,config:{iceServers:[{urls:"whatever"}]}})
const p2=new Peer()
p1.on("signal",s=>p2.signal(s))
p2.on("signal",s=>p1.signal(s))
p1.on("connect",_=>console.log("connected"))
p2.on("connect",_=>console.log("connected remote","id from my map","if the p1 is connected"))
```
what i get is 
`connected` for the initiator properly
`connected remote <id of p1 from my map> false` so p1 seems always not connected thus when i try to send data it just fails throwing error about `send of null` and if i do check the connected status the initiator peer never hears anything from the other peer but other peer can receive from the initiator.
I did try to use initiatorPeer.on("connect") on remote but it just never fires 

also i get error saying `Error: Ice Connection failed` after some time on remote peer

**Comment by t-mullen** [comment]
If you're getting that ICE error, it's likely you're not actually connected. The `send of null` error is because your peer has already been destroyed.

It's odd that you're getting the `connect` event on the initiator. My guess is the data channel is opening briefly before being destroyed.

You can debug ice failures by following the instructions in my comment here: 
https://github.com/feross/simple-peer/issues/202#issuecomment-378152065

**Comment by NikosEfthias** [comment]
@t-mullen  the problem is that this happens just between last two parties but others dont have any problem sending and receiving data from/to each other

**Comment by t-mullen** [comment]
I'm not entirely sure what you mean by "last two parties".

If you're getting an ice failure error constantly, there's likely some problem with that network or the way you are signalling. Try those steps to get rid of the error.

If you can get any odd behaviour without `Error: Ice Connection failed` feel free to reopen.
