### ISSUE TITLE
InvalidStateError: Failed to set remote answer sdp: Called in wrong state: kStable

### ISSUE THREAD

**Issue by chevalier37** [feross/simple-peer#395]
hey there,

I have implemented simple-peer.js and I have the error when I send the answer : 
**InvalidStateError: Failed to set remote answer sdp: Called in wrong state: kStable**

Here is my config : 

```
let p = new Peer({
  			 initiator: initiator,
  			 stream: stream,
  			 config:
  			  {
			    'iceServers': [
				     {
				      'urls': 'stun:eu-xxxxx.com'
				    },
				    {
				      'urls': 'turn:eu-xxxxx=udp',
				      'credential': 'xxxxxxxx',
				      'username': 'xxxxxx'
				    },
				  ]
				},
  			 trickle:false
  			})

```

Have you an idea to fix this error ?

**Comment by t-mullen** [comment]
That error means your signalling is in the wrong order.

**Comment by rabihiawaludin** [comment]
any idea?

**Comment by yo-png** [comment]
I have the same error

**Comment by nazar-pc** [comment]
If you have the same error than the same respose from Thomas applies, just check your apps, there must be something wrong the way you do signaling handling.

**Comment by werg** [comment]
There may be something like a resurgence of this problem in the most recent version of Chrome (maybe in interplay with simple-peer?): https://stackoverflow.com/questions/48963787/failed-to-set-local-answer-sdp-called-in-wrong-state-kstable

If I initiate sessions with a stream of both audio and video tracks I randomly get errors either setting local or remote answer or description. -- This problem is fixed if I initiate the peer with a stream of only one track.

Anybody else experiencing similar issues?

**Comment by godexsoft** [comment]
Yes @werg same here. 
Also, lolled at how many people are interested in making a video chat "all of a sudden" :)

**Comment by rawars** [comment]
Dude, I had the same problem and you can fix it by deploying the signaling server on port 8080.

Also I had to add these iceServers:
```javascript
const config = {
  'iceServers': [
      { url: 'stun:stun1.l.google.com:19302' },
      {
          url: 'turn:numb.viagenie.ca',
          credential: 'muazkh',
          username: 'webrtc@live.com'
      }
  ]
}
const peerConnection = new RTCPeerConnection(config);
```
I managed to deploy with the fixes on an amazon server.

**Comment by godexsoft** [comment]
@rawars Don't know about port 8080, that could only be a problem with your router's firewall possibly.
But for me the fix was doing the process in reverse: The newly joining peer only notifies everyone that they joined the call via the signaling server and instead of then opening all the RTCPeerConnections in a forEach you allow the other peers that are already on the call to call the newly joined peer. This way there was no issue with this state madness. I think it's some sort of async caused by my code not being perfect or possibly by some other deeper problems within the browser's implementation.. i can't be bothered to find out.

**Comment by godexsoft** [comment]
I have tracked down the issue by pure luck. Since most of us are probably started off the same tutorials... the issue only happens with more than 2 connections (peers). And the issue is this:

```
onSignalingMessage = data => {
        let msg = JSON.parse(data);

        // make sure the message is for us
        // this lines were missing but without this it's broken
        if (msg.from != this.peerClient)
            return;

// ... handling connection-answer, new-ice-candidate here ...
    ```

Basically what happens is you are trying to set an answer or ice-candidate on the wrong peer and they don't like it :)

Hope this helps.

**Comment by Dprosevski** [comment]
my error was because i was accidentally creating peer with the current user instead of the user im trying to connect to...

**Comment by smash-96** [comment]
WebRTC is a very complicated piece of technology. I was facing this issue due to the STUN/TURN servers. The freely available servers only work when all devices are on the same network. If devices are on different networks then we'll face various issues including one like this.
My advise is use free servers for testing while remaining on the same network. When deploying your app to production, you might have to build and host your own STUN/TURN servers or use Twiolio's NAT traversal service ([link](https://www.twilio.com/stun-turn))

**Comment by MeNearly** [comment]
Just saying, I experienced the same problem, and the cause was that I was resending the offer to myself...
Obviously, fixing my signaling server solved this :D
