### ISSUE TITLE
Mitigating "Failed to construct 'RTCPeerConnection'" errors

### ISSUE THREAD

**Issue by guanzo** [feross/simple-peer#422]
Due to this chromium bug, https://bugs.chromium.org/p/chromium/issues/detail?id=825576, RTCPeerConnection's are not being garbage collected in a timely manner. My webtorrent project seeds around 5 files, after a while I can see literally thousands of `Uncaught DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections` errors being thrown, eventually crashing the tab if it's left open long enough.

Until that bug is fixed, can we add a try/catch around the offending line? I can't seem to catch the error myself, as it occurs deep in webtorrent.

https://github.com/feross/simple-peer/blob/91c2fbe3006127550bff62a5b428bababa6b167a/index.js#L95

Are there any workarounds for this error?

**Comment by t-mullen** [comment]
There’s eventually going to be an error for too many peer connections - you’ll eventually run out of system resources. Not much we can do here about the garbage collection bug.

If the constructor throws uncaught errors we should catch them in a try block and emit them in the “error” event though. 

You might want to open an issue on the webtorrent repo if you think peers aren’t being manually destroyed, but 5 seperate file swarms is a lot in webtorrent

**Comment by jimmywarting** [comment]
I had a similar issue (unrelated to webtorrent and simple-peer) and i manage to work around that problem by having a pool of disposable ("reusable") peers that have not established a connection yet and where `iceConnectionState === 'new'`

Essentially all peer that don't get a sdp response back will not be destroyed. Instead the signal will be passed forward to another person. But that puts more responsibility on to you. You have to make sure that the person you are talking to really is the person you wanted to connect with.

An example with 3 person (Alice, Bob & Edward):
Alice wants to make a call to Bob (So she creates a RTCPeerConnection)
but Bob don't reply back, so instead of destroying Bobs and Alices RTCPeerConnection and create an all new RTCPeerConnection with a new sdp-offer Alice calls Edward instead and passes her already created sdp-offer from the first call along to Edward.
At this point you have to make sure that Bob can no longer reply back so you must stop or ignore others sdp-answer that will attempt to answer to Alice unless the sdp-answer comes from Edward.

This saves you time as ice gathering can take some time to get. and will make the end-to-end connection faster (reducing the time it takes for you to get a sdp) as you can pre-create RTCPeerConnection and gather all ices beforehand and not having to do it all over again.

**Comment by jimmywarting** [comment]
A hypothetical solution for when that error might occur might be to spin of a new hidden iframe (process) and create peers inside of that, then when you remove the iframe you can maybe be really sure that the RTCPeerConnection is really closed and garbage collected. but it sounds like a awful solution

**Comment by t-mullen** [comment]
It seems the Chrome team is aware of the bug and working to fix it - the most we should do is handle the error properly.

**Comment by guanzo** [comment]
Thanks @t-mullen. Hopefully webtorrent will update their `simple-peer` package soon.
