### ISSUE TITLE
Implement transceiver support.

### ISSUE THREAD

**Issue by t-mullen** [feross/simple-peer#433]
As discussed in #430, Unified plan does not permit non-initiators to add media lines. The initiator must instead create a transceivers for each media streams it wants to receive.

We can either expose `addTransceiver` or use the out-of-band "renegotiate" signal message to call `addTransceiver` on the initiator automatically during negotiation.

An urgent subset of #351.

**Comment by t-mullen** [comment]
We should also remove anything related to constraints since they don't do anything in Unified Plan.

**Comment by jarretttaylor** [comment]
@t-mullen,
I saw where you had built a new version (1593ca1), so I downloaded it and tried it with my app. I wasn't sure if it were ready for testing, but I went ahead and tried it. The addStream even didn't appear to fire on the receiving side (in my app). My logs follow:

**non-initiator (adding secondary stream):**
20:46:10.059 addStream()
20:46:10.062 addTrack()
20:46:10.065 _needsNegotiation
20:46:10.072 starting batched negotiation
20:46:10.075 requesting negotiation from initiator
20:46:10.123 signal()
20:46:10.139 signalingStateChange have-remote-offer
20:46:10.161 flushing sender queue
20:46:10.177 negotiate
20:46:10.177 signalingStateChange stable
20:46:10.177 signal

**initiator:**
20:46:10.079 simplepeer.min.js:11 signal()
20:46:10.080 simplepeer.min.js:11 got request to renegotiate
20:46:10.080 simplepeer.min.js:11 _needsNegotiation
20:46:10.083 simplepeer.min.js:11 starting batched negotiation
20:46:10.083 simplepeer.min.js:11 start negotiation
20:46:10.106 simplepeer.min.js:11 signalingStateChange have-local-offer
20:46:10.107 simplepeer.min.js:11 createOffer success
20:46:10.108 simplepeer.min.js:11 signal
20:46:10.181 simplepeer.min.js:11 signal()
20:46:10.212 simplepeer.min.js:11 flushing sender queue []
20:46:10.213 simplepeer.min.js:11 negotiate
20:46:10.213 simplepeer.min.js:11 signalingStateChange stable
20:46:14.562 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: complete)
20:46:14.562 simplepeer.min.js:11 maybeReady pc true channel true

**Comment by t-mullen** [comment]
Which browser?

**Comment by t-mullen** [comment]
It doesn't look like ice is completing. Your initiator logs are missing the `maybeReady pc true channel true` message. Can you connect on the current version?

**Comment by jarretttaylor** [comment]
@t-mullen Sorry about that. I should have included the browser/version. Here are my updated logs which show the initial connection and then the addition of a secondary stream from the non-inititiator approximately 20 seconds later. This scenario does not work. Note that trickle is set to true. I tested again with trickle set to false and it worked. I will post the logs from that as an additional comment to keep from spamming this entry.

**non-initiator trickle: true (ChromeOS 72.0.3626.122):**
21:14:04.400 signal()
21:14:04.417 signal()
21:14:04.421 signal()
21:14:04.422 signal()
21:14:04.425 signal()
21:14:04.426 signal()
21:14:04.429 signalingStateChange have-remote-offer
21:14:04.430 on track
21:14:04.430 on track
21:14:04.430 signal()
21:14:04.459 flushing sender queue
21:14:04.459 negotiate
21:14:04.460 signalingStateChange stable
21:14:04.461 signal
21:14:04.465 iceStateChange (connection: checking,new) (gathering: %s)
21:14:04.487 iceStateChange (connection: checking,gathering) (gathering: %s)
21:14:04.616 signal()
21:14:04.618 signal()
21:14:04.620 signal()
21:14:04.627 signal()
21:14:04.627 signal()
21:14:04.632 signal()
21:14:04.632 signal()
21:14:04.634 signal()
21:14:04.637 signal()
21:14:04.664 iceStateChange (connection: checking,complete) (gathering: %s)
21:14:04.675 iceStateChange (connection: connected,complete) (gathering: %s)
21:14:04.675 maybeReady pc true,false channel %s
21:14:04.684 on channel open
21:14:04.684 maybeReady pc true,true channel %s
21:14:04.688 connect local: 192.168.1.123,56592,192.168.1.144,51979:%s remote: %s:%s
21:14:04.689 connect
21:14:05.101 addStream()
21:14:05.101 addTrack()
21:14:05.103 _needsNegotiation
21:14:05.104 addTrack()
21:14:05.106 _needsNegotiation
21:14:05.111 starting batched negotiation
21:14:05.111 requesting negotiation from initiator
21:14:05.159 signal()
21:14:05.184 signalingStateChange have-remote-offer
21:14:05.223 flushing sender queue
21:14:05.224 negotiate
21:14:05.224 signalingStateChange stable
21:14:05.224 signal

21:14:24.054 addStream()
21:14:24.054 addTrack()
21:14:24.057 _needsNegotiation
21:14:24.063 starting batched negotiation
21:14:24.063 requesting negotiation from initiator
21:14:24.096 signal()
21:14:24.117 signalingStateChange have-remote-offer
21:14:24.148 flushing sender queue
21:14:24.148 negotiate
21:14:24.148 signalingStateChange stable
21:14:24.149 signal


**initiator trickle: true (Chrome 73.0.3683.86 Win10 64-bit):**
21:14:04.351 simplepeer.min.js:11 starting batched negotiation
21:14:04.351 simplepeer.min.js:11 start negotiation
21:14:04.385 simplepeer.min.js:11 signalingStateChange have-local-offer
21:14:04.387 simplepeer.min.js:11 createOffer success
21:14:04.388 simplepeer.min.js:11 signal
21:14:04.401 simplepeer.min.js:11 iceStateChange (connection: new) (gathering: gathering)
21:14:04.597 simplepeer.min.js:11 signal()
21:14:04.601 simplepeer.min.js:11 signal()
21:14:04.605 simplepeer.min.js:11 signal()
21:14:04.606 simplepeer.min.js:11 flushing sender queue []
21:14:04.607 simplepeer.min.js:11 negotiate
21:14:04.607 simplepeer.min.js:11 signalingStateChange stable
21:14:04.613 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
21:14:04.647 simplepeer.min.js:11 signal()
21:14:04.650 simplepeer.min.js:11 signal()
21:14:04.655 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: complete)
21:14:04.671 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: complete)
21:14:04.672 simplepeer.min.js:11 maybeReady pc true channel false
21:14:04.676 simplepeer.min.js:11 on channel open
21:14:04.677 simplepeer.min.js:11 maybeReady pc true channel true
21:14:04.681 simplepeer.min.js:11 connect local: 192.168.1.144:51979 remote: 192.168.1.123:56592
21:14:04.682 simplepeer.min.js:11 connect
21:14:05.114 simplepeer.min.js:11 signal()
21:14:05.115 simplepeer.min.js:11 got request to renegotiate
21:14:05.115 simplepeer.min.js:11 _needsNegotiation
21:14:05.117 simplepeer.min.js:11 starting batched negotiation
21:14:05.118 simplepeer.min.js:11 start negotiation
21:14:05.148 simplepeer.min.js:11 signalingStateChange have-local-offer
21:14:05.149 simplepeer.min.js:11 createOffer success
21:14:05.150 simplepeer.min.js:11 signal
21:14:05.232 simplepeer.min.js:11 signal()
21:14:05.292 simplepeer.min.js:11 flushing sender queue []
21:14:05.292 simplepeer.min.js:11 negotiate
21:14:05.293 simplepeer.min.js:11 signalingStateChange stable
21:14:05.294 simplepeer.min.js:11 on track
21:14:05.295 simplepeer.min.js:11 on track

21:14:19.892 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: complete)
21:14:19.892 simplepeer.min.js:11 maybeReady pc true channel true

21:14:24.064 simplepeer.min.js:11 signal()
21:14:24.065 simplepeer.min.js:11 got request to renegotiate
21:14:24.065 simplepeer.min.js:11 _needsNegotiation
21:14:24.067 simplepeer.min.js:11 starting batched negotiation
21:14:24.067 simplepeer.min.js:11 start negotiation
21:14:24.086 simplepeer.min.js:11 signalingStateChange have-local-offer
21:14:24.086 simplepeer.min.js:11 createOffer success
21:14:24.087 simplepeer.min.js:11 signal
21:14:24.153 simplepeer.min.js:11 signal()
21:14:24.164 simplepeer.min.js:11 flushing sender queue []
21:14:24.164 simplepeer.min.js:11 negotiate
21:14:24.164 simplepeer.min.js:11 signalingStateChange stable

**Comment by jarretttaylor** [comment]
@t-mullen These are the logs where trickle was set to false. The secondary stream worked in this scenario. Thanks for all your work on this.

non-initiator trickle: false (ChromeOS 72.0.3626.122):
21:24:57.261 signal()
21:24:57.307 signalingStateChange have-remote-offer
21:24:57.311 on track
21:24:57.311 on track
21:24:57.379 flushing sender queue
21:24:57.379 negotiate
21:24:57.379 signalingStateChange stable
21:24:57.379 iceStateChange (connection: checking,new) (gathering: %s)
21:24:57.379 iceStateChange (connection: checking,gathering) (gathering: %s)
21:24:57.383 started iceComplete timeout
21:24:57.615 iceStateChange (connection: checking,complete) (gathering: %s)
21:24:57.617 signal
21:24:57.739 iceStateChange (connection: connected,complete) (gathering: %s)
21:24:57.740 maybeReady pc true,false channel %s
21:24:57.754 on channel open
21:24:57.756 maybeReady pc true,true channel %s
21:24:57.760 connect local: 192.168.1.123,57854,192.168.1.144,50854:%s remote: %s:%s
21:24:57.760 connect
21:24:58.191 addStream()
21:24:58.192 addTrack()
21:24:58.198 _needsNegotiation
21:24:58.199 addTrack()
21:24:58.201 _needsNegotiation
21:24:58.203 starting batched negotiation
21:24:58.203 requesting negotiation from initiator
21:24:58.234 signal()
21:24:58.274 signalingStateChange have-remote-offer
21:24:58.321 flushing sender queue
21:24:58.322 negotiate
21:24:58.322 signalingStateChange stable
21:24:58.322 signal

21:25:18.377 addStream()
21:25:18.379 addTrack()
21:25:18.382 _needsNegotiation
21:25:18.387 starting batched negotiation
21:25:18.387 requesting negotiation from initiator
21:25:18.431 signal()
21:25:18.465 signalingStateChange have-remote-offer
21:25:18.491 flushing sender queue
21:25:18.492 negotiate
21:25:18.493 signalingStateChange stable
21:25:18.493 signal
21:25:18.497 requesting transceiver of kind
21:25:18.499 addTransceiver()
21:25:18.608 signal()
21:25:18.659 signalingStateChange have-remote-offer
21:25:18.669 iceStateChange (connection: disconnected,complete) (gathering: %s)
21:25:18.670 iceStateChange (connection: disconnected,gathering) (gathering: %s)
21:25:18.724 iceStateChange (connection: checking,gathering) (gathering: %s)
21:25:18.753 flushing sender queue
21:25:18.755 negotiate
21:25:18.755 signalingStateChange stable
21:25:18.755 signal
21:25:18.764 iceStateChange (connection: connected,gathering) (gathering: %s)
21:25:18.765 maybeReady pc true,true channel %s
21:25:18.765 iceStateChange (connection: connected,complete) (gathering: %s)
21:25:18.765 maybeReady pc true,true channel %s

initiator trickle: false (Chrome 73.0.3683.86 Win10 64-bit):
21:24:52.218 simplepeer.min.js:11 starting batched negotiation
21:24:52.219 simplepeer.min.js:11 start negotiation
21:24:52.246 simplepeer.min.js:11 signalingStateChange have-local-offer
21:24:52.247 simplepeer.min.js:11 createOffer success
21:24:52.249 simplepeer.min.js:11 iceStateChange (connection: new) (gathering: gathering)
21:24:52.250 simplepeer.min.js:11 started iceComplete timeout
21:24:57.252 simplepeer.min.js:11 iceComplete timeout completed
21:24:57.253 simplepeer.min.js:11 signal
21:24:57.620 simplepeer.min.js:11 signal()
21:24:57.630 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
21:24:57.634 simplepeer.min.js:11 flushing sender queue []
21:24:57.634 simplepeer.min.js:11 negotiate
21:24:57.634 simplepeer.min.js:11 signalingStateChange stable
21:24:57.681 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: complete)
21:24:57.736 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: complete)
21:24:57.737 simplepeer.min.js:11 maybeReady pc true channel false
21:24:57.744 simplepeer.min.js:11 on channel open
21:24:57.744 simplepeer.min.js:11 maybeReady pc true channel true
21:24:57.749 simplepeer.min.js:11 connect local: 192.168.1.144:50854 remote: 192.168.1.123:57854
21:24:57.749 simplepeer.min.js:11 connect
21:24:58.205 simplepeer.min.js:11 signal()
21:24:58.206 simplepeer.min.js:11 got request to renegotiate
21:24:58.206 simplepeer.min.js:11 _needsNegotiation
21:24:58.208 simplepeer.min.js:11 starting batched negotiation
21:24:58.208 simplepeer.min.js:11 start negotiation
21:24:58.224 simplepeer.min.js:11 signalingStateChange have-local-offer
21:24:58.224 simplepeer.min.js:11 createOffer success
21:24:58.225 simplepeer.min.js:11 signal
21:24:58.324 simplepeer.min.js:11 signal()
21:24:58.382 simplepeer.min.js:11 flushing sender queue []
21:24:58.383 simplepeer.min.js:11 negotiate
21:24:58.383 simplepeer.min.js:11 signalingStateChange stable
21:24:58.384 simplepeer.min.js:11 on track
21:24:58.385 simplepeer.min.js:11 on track

21:25:13.082 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: complete)
21:25:13.082 simplepeer.min.js:11 maybeReady pc true channel true

21:25:18.390 simplepeer.min.js:11 signal()
21:25:18.390 simplepeer.min.js:11 got request to renegotiate
21:25:18.391 simplepeer.min.js:11 _needsNegotiation
21:25:18.393 simplepeer.min.js:11 starting batched negotiation
21:25:18.393 simplepeer.min.js:11 start negotiation
21:25:18.423 simplepeer.min.js:11 signalingStateChange have-local-offer
21:25:18.424 simplepeer.min.js:11 createOffer success
21:25:18.425 simplepeer.min.js:11 signal
21:25:18.497 simplepeer.min.js:11 signal()
21:25:18.508 simplepeer.min.js:11 signal()
21:25:18.509 simplepeer.min.js:11 got request for transceiver
21:25:18.509 simplepeer.min.js:11 addTransceiver()
21:25:18.516 simplepeer.min.js:11 _needsNegotiation
21:25:18.523 simplepeer.min.js:11 flushing sender queue []
21:25:18.524 simplepeer.min.js:11 negotiate
21:25:18.524 simplepeer.min.js:11 signalingStateChange stable
21:25:18.526 simplepeer.min.js:11 starting batched negotiation
21:25:18.526 simplepeer.min.js:11 start negotiation
21:25:18.574 simplepeer.min.js:11 signalingStateChange have-local-offer
21:25:18.574 simplepeer.min.js:11 createOffer success
21:25:18.576 simplepeer.min.js:11 signal
21:25:18.581 simplepeer.min.js:11 iceStateChange (connection: disconnected) (gathering: complete)
21:25:18.581 simplepeer.min.js:11 iceStateChange (connection: disconnected) (gathering: gathering)
21:25:18.770 simplepeer.min.js:11 signal()
21:25:18.898 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
21:25:18.906 simplepeer.min.js:11 flushing sender queue []
21:25:18.906 simplepeer.min.js:11 negotiate
21:25:18.907 simplepeer.min.js:11 signalingStateChange stable
21:25:18.908 simplepeer.min.js:11 on track
21:25:18.915 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: gathering)
21:25:18.915 simplepeer.min.js:11 maybeReady pc true channel true
21:25:18.917 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: gathering)
21:25:18.918 simplepeer.min.js:11 maybeReady pc true channel true
21:25:18.918 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: complete)
21:25:18.919 simplepeer.min.js:11 maybeReady pc true channel true

**Comment by t-mullen** [comment]
Can you log all of the signalling messages emitted by each peer?

```javascript
peer.on('signal', (data) => {
  console.log(data)
})
```

**Comment by jarretttaylor** [comment]
@t-mullen Disregard my comment regarding trickle true vs false. In both scenarios, it is working sometimes and not others. I need to create a more controlled/consistent test scenario before I post any more logs.

**Comment by jarretttaylor** [comment]
@t-mullen Ok... new logs (with trickle: false, although the experience is similar with trickle: true). The first time I add the second stream from the non-initiator, it works. Then, when I attempt to remove that stream and add another one, it fails. If I try to add the second stream repeatedly (manually, via clicking a button), it will eventually work (that is not reflected in these logs). I wonder if it is some sort of race condition in the renegotiation since it is removing and adding in close proximity.

**non-initiator (Chrome 73.0.3683.86 Win10 64-bit)**
<details>
        <summary>Click to expand</summary>
13:08:45.030 simplepeer.min.js:11 starting batched negotiation
13:09:04.713 simplepeer.min.js:11 signal()
13:09:04.986 simplepeer.min.js:11 signalingStateChange have-remote-offer
13:09:05.001 simplepeer.min.js:11 on track
13:09:05.731 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: new)
13:09:05.757 simplepeer.min.js:11 flushing sender queue []
13:09:05.833 simplepeer.min.js:11 negotiate
13:09:05.834 simplepeer.min.js:11 signalingStateChange stable
13:09:05.835 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
13:09:05.902 simplepeer.min.js:11 started iceComplete timeout
13:09:06.234 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: complete)
13:09:06.236 simplepeer.min.js:11 signal
13:09:06.239 simplepeer.min.js:11 requesting transceiver of kind audio
13:09:06.240 simplepeer.min.js:11 addTransceiver()
13:09:06.372 simplepeer.min.js:11 signal()
13:09:07.056 simplepeer.min.js:11 signalingStateChange have-remote-offer
13:09:07.242 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
13:09:07.399 simplepeer.min.js:11 on channel open
13:09:07.399 simplepeer.min.js:11 maybeReady pc false channel true
13:09:07.414 simplepeer.min.js:11 flushing sender queue []
13:09:07.416 simplepeer.min.js:11 negotiate
13:09:07.417 simplepeer.min.js:11 signalingStateChange stable
13:09:07.420 simplepeer.min.js:11 signal
13:09:07.440 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: gathering)
13:09:07.440 simplepeer.min.js:11 maybeReady pc true channel true
13:09:07.466 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: complete)
13:09:07.466 simplepeer.min.js:11 maybeReady pc true channel true
13:09:07.653 simplepeer.min.js:11 connect local: 192.168.1.140:50103 remote: 192.168.1.144:56098
13:09:07.653 simplepeer.min.js:11 connect

//adding of the second stream
13:09:36.876 simplepeer.min.js:11 addStream()
13:09:36.878 simplepeer.min.js:11 addTrack()
13:09:36.891 simplepeer.min.js:11 _needsNegotiation
13:09:36.896 simplepeer.min.js:11 starting batched negotiation
13:09:36.898 simplepeer.min.js:11 requesting negotiation from initiator
13:09:36.925 simplepeer.min.js:11 signal()
13:09:36.947 simplepeer.min.js:11 signalingStateChange have-remote-offer
13:09:36.977 simplepeer.min.js:11 flushing sender queue []
13:09:36.979 simplepeer.min.js:11 negotiate
13:09:36.980 simplepeer.min.js:11 signalingStateChange stable
13:09:36.982 simplepeer.min.js:11 signal
13:09:37.022 simplepeer.min.js:11 requesting transceiver of kind video
13:09:37.023 simplepeer.min.js:11 addTransceiver()
13:09:37.080 simplepeer.min.js:11 signal()
13:09:37.103 simplepeer.min.js:11 signalingStateChange have-remote-offer
13:09:37.107 simplepeer.min.js:11 iceStateChange (connection: disconnected) (gathering: complete)
13:09:37.107 simplepeer.min.js:11 iceStateChange (connection: disconnected) (gathering: gathering)
13:09:37.191 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
13:09:37.202 simplepeer.min.js:11 flushing sender queue []
13:09:37.205 simplepeer.min.js:11 negotiate
13:09:37.206 simplepeer.min.js:11 signalingStateChange stable
13:09:37.212 simplepeer.min.js:11 signal
13:09:37.218 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: gathering)
13:09:37.218 simplepeer.min.js:11 maybeReady pc true channel true
13:09:37.219 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: complete)
13:09:37.220 simplepeer.min.js:11 maybeReady pc true channel true

//removing the existing second stream
13:10:20.472 simplepeer.min.js:11 removeSenders()
13:10:20.473 simplepeer.min.js:11 removeSender()

//adding a new second stream (fails)
13:10:21.161 simplepeer.min.js:11 addStream()
13:10:21.162 simplepeer.min.js:11 addTrack()
13:10:21.188 simplepeer.min.js:11 _needsNegotiation
13:10:21.196 simplepeer.min.js:11 starting batched negotiation
13:10:21.232 simplepeer.min.js:11 requesting negotiation from initiator
13:10:21.284 simplepeer.min.js:11 signal()
13:10:21.307 simplepeer.min.js:11 signalingStateChange have-remote-offer
13:10:21.359 simplepeer.min.js:11 flushing sender queue []
13:10:21.360 simplepeer.min.js:11 negotiate
13:10:21.362 simplepeer.min.js:11 signalingStateChange stable
13:10:21.367 simplepeer.min.js:11 signal
		</details>

**initiator (Chrome 73.0.3683.86 Win10 64-bit)**
	<details>
        <summary>Click to expand</summary>
13:08:59.187 simplepeer.min.js:11 starting batched negotiation
13:08:59.189 simplepeer.min.js:11 start negotiation
13:08:59.217 simplepeer.min.js:11 signalingStateChange have-local-offer
13:08:59.218 simplepeer.min.js:11 createOffer success
13:08:59.220 simplepeer.min.js:11 iceStateChange (connection: new) (gathering: gathering)
13:08:59.222 simplepeer.min.js:11 started iceComplete timeout
13:09:04.223 simplepeer.min.js:11 iceComplete timeout completed
13:09:04.224 simplepeer.min.js:11 signal
13:09:05.802 simplepeer.min.js:11 signal()
13:09:05.815 simplepeer.min.js:11 signal()
13:09:05.815 simplepeer.min.js:11 got request for transceiver
13:09:05.816 simplepeer.min.js:11 addTransceiver()
13:09:05.865 simplepeer.min.js:11 _needsNegotiation
13:09:05.867 simplepeer.min.js:11 flushing sender queue []
13:09:05.868 simplepeer.min.js:11 negotiate
13:09:05.868 simplepeer.min.js:11 signalingStateChange stable
13:09:05.869 simplepeer.min.js:11 on track
13:09:05.870 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
13:09:05.871 simplepeer.min.js:11 starting batched negotiation
13:09:05.871 simplepeer.min.js:11 start negotiation
13:09:05.903 simplepeer.min.js:11 signalingStateChange have-local-offer
13:09:05.904 simplepeer.min.js:11 createOffer success
13:09:05.906 simplepeer.min.js:11 signal
13:09:05.995 simplepeer.min.js:11 on channel open
13:09:05.996 simplepeer.min.js:11 maybeReady pc false channel true
13:09:06.971 simplepeer.min.js:11 signal()
13:09:06.986 simplepeer.min.js:11 flushing sender queue []
13:09:06.987 simplepeer.min.js:11 negotiate
13:09:06.987 simplepeer.min.js:11 signalingStateChange stable
13:09:07.018 simplepeer.min.js:11 on track
13:09:07.021 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: gathering)
13:09:07.022 simplepeer.min.js:11 maybeReady pc true channel true
13:09:07.023 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: complete)
13:09:07.023 simplepeer.min.js:11 maybeReady pc true channel true
13:09:07.028 simplepeer.min.js:11 connect local: 192.168.1.144:56098 remote: 192.168.1.140:50103
13:09:07.029 simplepeer.min.js:11 connect

13:09:21.103 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: complete)
13:09:21.103 simplepeer.min.js:11 maybeReady pc true channel true

//triggered by the adding of the second stream
13:09:36.445 simplepeer.min.js:11 signal()
13:09:36.445 simplepeer.min.js:11 got request to renegotiate
13:09:36.446 simplepeer.min.js:11 _needsNegotiation
13:09:36.447 simplepeer.min.js:11 starting batched negotiation
13:09:36.447 simplepeer.min.js:11 start negotiation
13:09:36.461 simplepeer.min.js:11 signalingStateChange have-local-offer
13:09:36.462 simplepeer.min.js:11 createOffer success
13:09:36.463 simplepeer.min.js:11 signal
13:09:36.567 simplepeer.min.js:11 signal()
13:09:36.574 simplepeer.min.js:11 signal()
13:09:36.574 simplepeer.min.js:11 got request for transceiver
13:09:36.575 simplepeer.min.js:11 addTransceiver()
13:09:36.581 simplepeer.min.js:11 _needsNegotiation
13:09:36.582 simplepeer.min.js:11 flushing sender queue []
13:09:36.583 simplepeer.min.js:11 negotiate
13:09:36.583 simplepeer.min.js:11 signalingStateChange stable
13:09:36.584 simplepeer.min.js:11 starting batched negotiation
13:09:36.586 simplepeer.min.js:11 start negotiation
13:09:36.611 simplepeer.min.js:11 signalingStateChange have-local-offer
13:09:36.612 simplepeer.min.js:11 createOffer success
13:09:36.613 simplepeer.min.js:11 signal
13:09:36.615 simplepeer.min.js:11 iceStateChange (connection: disconnected) (gathering: complete)
13:09:36.615 simplepeer.min.js:11 iceStateChange (connection: disconnected) (gathering: gathering)
13:09:36.788 simplepeer.min.js:11 signal()
13:09:36.852 simplepeer.min.js:11 iceStateChange (connection: checking) (gathering: gathering)
13:09:36.853 simplepeer.min.js:11 flushing sender queue []
13:09:36.854 simplepeer.min.js:11 negotiate
13:09:36.854 simplepeer.min.js:11 signalingStateChange stable
13:09:36.855 simplepeer.min.js:11 on track
13:09:36.855 simplepeer.min.js:11 iceStateChange (connection: connected) (gathering: gathering)
13:09:36.855 simplepeer.min.js:11 maybeReady pc true channel true
13:09:36.856 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: gathering)
13:09:36.856 simplepeer.min.js:11 maybeReady pc true channel true
13:09:36.866 simplepeer.min.js:11 iceStateChange (connection: completed) (gathering: complete)
13:09:36.867 simplepeer.min.js:11 maybeReady pc true channel true

//triggered by the removal of the second stream/addition of new second stream?
13:10:20.782 simplepeer.min.js:11 signal()
13:10:20.782 simplepeer.min.js:11 got request to renegotiate
13:10:20.782 simplepeer.min.js:11 _needsNegotiation
13:10:20.784 simplepeer.min.js:11 starting batched negotiation
13:10:20.785 simplepeer.min.js:11 start negotiation
13:10:20.814 simplepeer.min.js:11 signalingStateChange have-local-offer
13:10:20.814 simplepeer.min.js:11 createOffer success
13:10:20.816 simplepeer.min.js:11 signal
13:10:20.912 simplepeer.min.js:11 signal()
13:10:20.928 simplepeer.min.js:11 flushing sender queue []
13:10:20.928 simplepeer.min.js:11 negotiate
13:10:20.928 simplepeer.min.js:11 signalingStateChange stable
		</details>

**Comment by t-mullen** [comment]
So the issue only occurs after removing a stream?

**Comment by jarretttaylor** [comment]
That is correct. Generally, my remove and subsequent add are within milliseconds of each of each other. However, I have run a scenario where I remove the secondary stream and then wait a minute or longer to see what happens. It doesn't appear that any renegotiation takes place when that happens (which might be ok).

I have found that after removing the second stream and attempting to add a new second stream (which fails), if I try to add the new second stream again, it works.

**Comment by t-mullen** [comment]
You aren't re-adding the same stream, are you?

**Comment by t-mullen** [comment]
Alright I've managed to reproduce this, working on a fix.

**Comment by t-mullen** [comment]
@jarretttaylor Can you try the latest committed build?

**Comment by jarretttaylor** [comment]
@t-mullen I am out of town this weekend, but I should be able to try it tomorrow (Sunday) night. Please post the commit number so I can make sure I grab the correct version.

**Comment by t-mullen** [comment]
Commit is 3581d04e74d728069cb5d30e638bafa67326af85. No rush, thanks for verifying.

**Comment by jarretttaylor** [comment]
@t-mullen Yes, this behavior only occurs when removing a stream and the adding a new/different stream.

**Comment by jarretttaylor** [comment]
@t-mullen Your latest change appears to have corrected by issue. I am able to repeatedly add and remove (and re-add) secondary streams from the non-initiator now. Thank you :)
