### ISSUE TITLE
Event for when stream is removed?

### ISSUE THREAD

**Issue by bradisbell** [feross/simple-peer#512]
We can call `peer.removeStream()`, and this appears to work fine.  I'm curious though if on the receiving end, the peer has some sort of event for when this happens?  Or, is there some sort of event on the stream where we know that it's totally done?  (Or, is this just looping through tracks and removing them one-by-one under the hood, in which case we should use the `removetrack` event on the MediaStream?)

**Comment by mturnshek** [comment]
I have the same problem. I'll try using the `onremovetrack` handler on my `mediaStream` and report back with the results.

**Comment by t-mullen** [comment]
There wasn't a reliable way to detect when tracks are removed when I added the current Unified Plan implementation. I'm not sure if anything has changed since then. The `removetrack` event on MediaStreams wasn't reliable in all browsers at that time either.

You can mute the track instead of removing it, and then listen for the `mute` event on the other side. This isn't performant if you plan on adding/removing a large number of tracks since muted tracks still send silence/black frames, but is the correct way to mute of tracks you plan to eventually unmute.

```javascript
peer.addTrack(track, stream)
track.enabled = true // to unmute
track.enabled = false // to mute
```
```javascript
peer.on('track', (track, stream) => {
  track.addEventListener('mute', () => {
    // track was muted by remote
  })
  track.addEventListener('unmute', () => {
    // track was unmuted by remote
  })
})
```

**Comment by kishorenc** [comment]
Setting the `enabled` property does not dispatch the `mute` event. I have tried both with Simplepeer and on a standalone mediastreamtrack example. It seems like they are not related.

See this related discussion: https://github.com/w3c/mediacapture-fromelement/issues/80

**Comment by t-mullen** [comment]
@kishorenc This used to work, but you're right it's not in the specification. It seems browsers have fixed this behaviour.

It looks like the `removetrack` event has also been removed from the spec. The new behaviour is to fire a `mute` event on the remote track.

> When the other peer stops sending a track in this manner, the track is removed from any remote MediaStreams that were initially revealed in the track event, and if the MediaStreamTrack is not already muted, a mute event is fired at the track.

**Comment by t-mullen** [comment]
Closing since the `mute` event is the spec-compliant way to detect track removal. We support this in simple-peer already.
