### ISSUE TITLE
Git tags missing for newer releases

### ISSUE THREAD

**Issue by longsleep** [feross/simple-peer#514]
It seems hat the for newer releases than v9.1.2 are not pushed to GitHub. Would be great if the tags can pushed so that it becomes clear what code is in which release found on NPM. Thanks!

**Comment by feross** [comment]
@longsleep I just added the missing git tags and pushed them to GitHub: https://github.com/feross/simple-peer/releases though I was a bit confused about when exactly 9.2.1 was published because I couldn't find the commit that bumped that version.

@t-mullen I think you did the past few releases, right?I'll share my publish scripts in case they're useful to you. It makes it less likely to forget an important step during publish.

```
alias patch='preversion && npm version patch && postversion'
alias minor='preversion && npm version minor && postversion'
alias major='preversion && npm version major && postversion'
alias preversion='git pull && git diff --exit-code && git diff --staged --exit-code && npm pack --dry-run --ignore-scripts && rm -rf node_modules/ && npm install && npm test'
alias postversion='git diff --exit-code && git diff --staged --exit-code && npm run --if-present update-authors && (git diff --exit-code || git commit -am "update authors") && npm run --if-present build && (git diff --exit-code || git commit -am "build") && git push && git push --tags && npm publish'
```

With these aliases in place, you can just run `patch`, `minor`, or `major` to publish a new version. It will automatically: 

- Pull the latest changes from GitHub
- Ensure that your git tree is clean
- List the files that will be included in the published package
- Do a fresh npm install
- Run the tests
- Increment the npm version and commit it
- Add a git tag for the npm version
- Run the `update-authors` script (if present)
  - If any files were changed, commit them with the message "update authors"
- Run the `build` script (if present)
  - If any files were changed, commit them with the message "build"
- Push the commits and the git tags
- Publish the new version to npm

Hopefully this is helpful :)

**Comment by t-mullen** [comment]
@feross Thanks! Those are very helpful.
