### ISSUE TITLE
Full example please..

### ISSUE THREAD

**Issue by pavelvasev** [feross/simple-peer#53]
Could you please provide a folder with full example files?

As for me, this folder should contain:

1. Some html page for browsers
2. Some nodejs app 
3. Connection server?
4. Relay server?

Thus we, the newbie developers, might got it all work and test and use as a starter kit for our apps.

Is that possible?...  Thank you in advance! 
Pavel

**Comment by feross** [comment]
This package does not have an opinion about what type of signaling server or node.js app you use. We have a complete example in the readme, [here](https://github.com/feross/simple-peer#usage).

If someone else has a good link to a full example, please share to help @pavelvasev out.

Otherwise, I recommend you just read http://www.html5rocks.com/en/tutorials/webrtc/basics/ and try using this package afterwards.
