### ISSUE TITLE
Chrome m76 simple-peer doesn't destroy after disconnection (nor emits 'close')

### ISSUE THREAD

**Issue by perkio** [feross/simple-peer#532]
this is due to a breaking change in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=982793

**Comment by paulalbertdev** [comment]
So, how do you advise to handle disconnections with simple-peer now ?

**Comment by paulalbertdev** [comment]
Since you've labelled this as a bug, I presume you're going need to write a workaround... 
Thanks, and keep up the good work !

**Comment by t-mullen** [comment]
It seems checking for `pc.connectionState === 'failed'` on a `connectionstatechange` event would work. We should probably destroy the peer if this happens anyways.

**Comment by t-mullen** [comment]
Options 1 seems to be the correct solution. We should be destroying the peer on the terminal `connectionState == 'failed'` irregardless of this issue.

Reverting to Plan B will almost certainly cause interop issues when using multiple media streams. You might have more severe issues with Safari since Plan B support there is very poor. This may have all been fixed (we don't test Plan B), but I doubt it.

I should have time to PR the connectionState check and write a few tests this weekend - sorry for the delay 👍
