### ISSUE TITLE
Dynamic video/voice does not work.

### ISSUE THREAD

**Issue by MariasStory** [feross/simple-peer#584]
Hi,
I did a simple example, similar to "dynamic video/voice".
".on('stream', stream => {" is triggered, but there is no video.

Does someone has such example working online?

**Comment by nazar-pc** [comment]
The example should work. Can you tell a bit about your setup?

**Comment by JuanSevillano** [comment]
When I use peer.addStream() it doesn't trigger the 

peer.on('stream', stream => { console.log('...nothing') })

**Comment by MariasStory** [comment]
Hi @nazar-pc,

It is the example from the github start page. I use socket.io for signal exchange. At first the data channel is open and than on key press the stream is send. I get the ".on('stream'", but no stream inside.

Single page example is working.

The best way is to setup a simplest example online ;-)

@JuanSevillano, it seems that I got a bit farther.

BZW: I already have webrtc solution working on another framework. Just wanted to see if simple-peer will do the job.

**Comment by nazar-pc** [comment]
If single page example works, it means you probably have a problem in signaling.
Make sure you handle signaling even after connection was established, since dynamic addition of streams will require re-negotiation.

**Comment by MariasStory** [comment]
Hi @nazar-pc,

I got the example working.
The problem was on the client side, the peer was re-initialized when the second offer was received.

Although, it would be nice to have few online examples, this issue can be closed.

Thanks

**Comment by nazar-pc** [comment]
Glad to know the issue was resolved!

**Comment by janesenaj** [comment]
Hello,

I tried to implement something similar to the 'dynamic video/voice' code, but `peer.addStream(stream)` did not trigger `peer.on('stream', ()=>{})`, and there's no error logs.

I have a mesh network so I stored all the peer objects in a list.

```
var peer = new Peer();
list.push(peer);
peer.on('stream', () => {
   console.log('stream obtained');
   // should display stream in video tag
});
.
.
.

addVideoStream(peerIdx, stream) {
   var peer = list[peerIdx];
  peer.addStream(stream);
}
```

`addVideoStream(stream)` is called on a button press, when required. 

Any help would be appreciated, thank you.

**Comment by amankrokx** [comment]
> Hello,
> 
> I tried to implement something similar to the 'dynamic video/voice' code, but `peer.addStream(stream)` did not trigger `peer.on('stream', ()=>{})`.
> 
> I have a mesh network so I stored all the peer objects in a list.
> 
> ```
> var peer = new Peer();
> list.push(peer);
> peer.on('stream', () => {
>    console.log('stream obtained');
>    // should display stream in video tag
> });
> .
> .
> .
> 
> addVideoStream(peerIdx, stream) {
>    var peer = list[peerIdx];
>   peer.addStream(stream);
> }
> ```
> 
> `addVideoStream(stream)` is called on a button press, when required. Although `peer.on('stream', ()=>{})` is not triggered, I see the following error when spamming the `addVideoStream(stream)` function:
> 
> > core.js:6185 ERROR Error: Track has already been added to that stream.
> 
> Any help would be appreciated, thank you.
> 
> EDIT: #557 solved my problem. I wasn't catching the peer.on('signal') that was fired when peer.addStream() is called.

hey !
I'm trying to to create something and i too am unable to get the .on('stream', ...) event, for testing i am copying and pasting JSON and clicking with button triggers, just wanna create a voice call app,
please point me to correct direction

`var conn = false
var answered = false
var bigPeer
function start(tr){
    p = new SimplePeer({
    initiator: tr,
    trickle: false
  })

  p.on('close', () => {
    p.destroy()
    bigPeer = null
    conn = false
  })

  p.on('data', data => {
    console.log('data: ' + data)
  })

  p.on('stream', stream => {
    // got remote video stream, now let's show it in a video tag
    console.log(stream);
    if ('srcObject' in video) {
      audio.srcObject = stream
    } else {
      audio.src = window.URL.createObjectURL(stream) // for older browsers
    }

    audio.play()
  })

  return p
}

function makePeer(){
  conn = false
  let peer = start(true)
  peer.on('signal', data => {
    if(!conn){
      console.log(JSON.stringify(data))
    }
  })

  p.on('error', err => console.log('error', err))

  bigPeer = peer
}

function answerPeer(address) {
  let peer = start(false)
  peer.on('signal', data => {
    //put to console for now
    console.log(JSON.stringify(data))
  })
  peer.signal(JSON.parse(address))
  
  peer.on('connect', () => {
    console.log('CONNECTED as non init')
    conn = true
    peer.send('whatever from non init' + Math.random())
  })
  bigPeer = peer
}

function answerAnswer(address) {
  let peer = bigPeer
  peer.signal(JSON.parse(address))

  peer.on('connect', () => {
    console.log('CONNECTED as init')
    conn = true
    peer.send('whatever from init' + Math.random())

  })
}

function msgPeer() {
  if(conn) bigPeer.send('test data' + Math.random())
}

var audio
window.onload = function() {
  audio = document.getElementById("audio")
  console.log(audio)
  $("#peertest button").eq(4).click(function(){
    if (conn) {
      //startListen()
      startAudio()
    }
  });
}


function startAudio() {
  if(navigator.getUserMedia) { // Standard
      navigator.getUserMedia({audio: true}, function(stream) {
        if(conn) {
          console.log('audio stream sent')
          bigPeer.addStream(stream)
        }
      }, (err) => {console.log(err)})
  } else if(navigator.webkitGetUserMedia) { // WebKit-prefixed
      navigator.webkitGetUserMedia({audio: true}, function(stream){
        if(conn) {
          console.log('audio stream sent')
          bigPeer.addStream(stream)
        }
      }, (err) => {console.log(err)})
  }
}`

**yes, i've added them inside function because i wanna fire them when needed only**

**Comment by AAAAsea** [comment]
> If single page example works, it means you probably have a problem in signaling. Make sure you handle signaling even after connection was established, since dynamic addition of streams will require re-negotiation.

I deleted the signalEvent when I firstly fired it, which causes no re-negotiation.  Appreciate!
