### ISSUE TITLE
Connect to another peer

### ISSUE THREAD

**Issue by middleftw** [feross/simple-peer#591]
I have read the documentation but how do I actually connect to another peer ?
```
var Peer = require('simple-peer')
var peer1 = new Peer({ initiator: true })
```
What am I supposed to do after this? The documentation is not that clear.What would the other peer have to share with the first peer in order to connect and what method does the actual connection ?

Thanks.

**Comment by IceHacks** [comment]
Wondering the same thing... (coming from `peerjs` which didn't work when I used it)

**Comment by nazar-pc** [comment]
Readme contains examples which you can copy and paste and they will work.
`peer1` in those examples represent one side of conversation and `peer2` the other.
You will need to replace signaling with something like WebSocket though if you want to run them in different browser. Other than that it should answer your question.

Otherwise try to look up general information about WebRTC and how it works, it will then make much more sense.
