### ISSUE TITLE
addTrack and removeTrack not working

### ISSUE THREAD

**Issue by saagarbethi** [feross/simple-peer#606]
i have tried to on/off video using addTrack and remove Track but not working

        `   document.getElementById('stopVedio').addEventListener('click', function () {
                 peer1.removeTrack(stream.getVideoTracks()[0], stream);
                })
                 document.getElementById('startVedio').addEventListener('click', function () {
                     peer1.addTrack(stream.getVideoTracks()[0] stream);
                })`
error  : Track has been removed. You should enable/disable tracks that you want to re-add

**Comment by nazar-pc** [comment]
Indeed, you should better enable/disable tracks by changing `enabled` field instead of adding/removing them, which in turn requires renegotiation and is more nuanced than you may want it to be.
Adding/removing should also work, but you will need to create a new track for that.

**Comment by AidanNelson** [comment]
@nazar-pc Is there a workaround which allows adding of previously removed mediaTracks?   

For  background: I'm attempting a full mesh topology, in which each peer-to-peer stream quality is determined by the distance between the two peers in a 3D environment.  The whole project is similar to VR chat or Mozilla Hubs.  I had planned to store a high, middle and low quality stream and swap them out for each peer.  Enabling / disabling mediaStream tracks doesn't work in this situation because it would affect all peer connections using a given mediaStream.

Thanks!

**Comment by nazar-pc** [comment]
@AidanNelson sounds like you want to use replaceTrack() API instead of adding/removing it. Also you can clone it and then it would appear as a new distinct track while being the same internally: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/clone

**Comment by AidanNelson** [comment]
That seems to work.  Thank you!

**Comment by mitschabaude** [comment]
Hi, first of all, thanks for the fantastic library.

I'm running across this problem, and I want to cautiously question whether the current behavior of `simple-peer` is really the right one or if there could be a better approach.

I understand that for typical use cases like mute/unmute, enable/disable track is the better solution, and you want to discourage using add/remove track for that reason. But that nudging could also be accomplished with a warning instead of an error.

As far as I can tell from the code, the error could simply be avoided by not throwing it. Instead, if a track is added that has previously been removed, you could treat it like a new track:

```js
// in addTrack()
if (!sender || sender.removed) {
  sender = this._pc.addTrack(track, stream);
  submap.set(stream, sender);
  this._senderMap.set(track, submap);
  this._needsNegotiation();
} else { ... }
```

This would replace the current code which throws if `sender.removed`:

```js
// in addTrack()
if (!sender) {
  sender = this._pc.addTrack(track, stream);
  submap.set(stream, sender);
  this._senderMap.set(track, submap);
  this._needsNegotiation();
} else if (sender.removed) {
  throw errCode(
    new Error(
      'Track has been removed. You should enable/disable tracks that you want to re-add.'
    ),
    'ERR_SENDER_REMOVED'
  );
} else { ... }
```

In a quick test, there seems to be no problem introduced by this approach, just one solved.

But of course, you know the code much better than I am, so maybe I am missing something? Are there deeper reasons for the error other than "you should not do this"?

For context, the recommended workaround of cloning the track is incredibly leaky if you're also using the track in other parts of your app. For example if the track is streamed to multiple peers... do they all have to get the new, cloned track now, or should I juggle multiple clones? Or if you use the track to visualize the volume of a speaker, etc.

The current approach seems to needlessly make the library harder to use.

If there are no objections to my fix, I'd be happy to make it a PR :)
