### ISSUE TITLE
How to do clean up in react 

### ISSUE THREAD

**Issue by vj-abishek** [feross/simple-peer#618]
```
useEffect(() => {
    const update = (newData) => {
      setMessage([...message, newData])    
    }
    peer.on('data', (data) => {     
      const parsed = JSON.parse(data)
      update(data)
     }
  return () => console.log("How to do Clean up")  
  }, [message])
```
This is not an issue with `simple-peer` . I want to know how to clean up peer in react hooks. 
Is there any other ways to use simple-peer with react. This code is showing warnings like:-
>maxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroy listeners added. Use emitter.setMaxListeners() to increase limit

If it is a `socket.io` connection I can clean up by using
```
useEffect(() => {
    const update = (newData) => {
      setMessage([...message, newData])    
    }
    socket.on('data', (data) => {     
      const parsed = JSON.parse(data)
      update(data)
     }
  return () => socket.off('data')
  }, [message])
```

*But I don't know how to clean up in simple-peer , any one please help me*

**Comment by nazar-pc** [comment]
With questions like this you'd have higher chances of getting answers on StackOverflow or similar thematic forums. If this is not an issue with simple-peer in any way, there is really no point in asking completely unrelated question about React in here.

If everyone asks about every possible use case of something + simple-peer then simple-peer maintainers will be overwhelmed with useless questions and would have less time to handle real ones.

I'm closing issue, since there is nothing to be done, hope you understand.
