### ISSUE TITLE
Is simple-peer supposed to work with wrtc?

### ISSUE THREAD

**Issue by paulkernfeld** [feross/simple-peer#62]
I see that the unit tests are a little flaky when I run this with wrtc. Is this library supposed to work with wrtc? Or, if not, is there an alternative node WebRTC implementation that I should use?

Example flakiness:
```
# data send/receive text
ok 3 (unnamed assert)
ok 4 (unnamed assert)
ok 5 peer1 is initiator
ok 6 peer2 is not initiator
ok 7 should be equal
ok 8 should be equal
not ok 9 should be equal
  ---
    operator: equal
    expected: '192.168.0.7'
    actual:   '10.186.1.6'
    at: Peer.tryTest (/Users/paul/repos/simple-peer/test/basic.js:59:7)
  ...
not ok 10 should be equal
  ---
    operator: equal
    expected: 52618
    actual:   59272
    at: Peer.tryTest (/Users/paul/repos/simple-peer/test/basic.js:60:7)
  ...
ok 11 (unnamed assert)
ok 12 (unnamed assert)
ok 13 (unnamed assert)
ok 14 (unnamed assert)
ok 15 got correct message
ok 16 got correct message
ok 17 both peers closed
```

**Comment by feross** [comment]
I removed `wrtc` from the tests a while ago because it's so difficult to build on lots of platforms. I haven't been able to get it to compile for a few months. If we can support it, I'd obviously like to. But I wouldn't call it officially supported in the same way that Chrome, Firefox, and Opera are.
