### ISSUE TITLE
Kurento Video Record

### ISSUE THREAD

**Issue by ahmetozalp** [feross/simple-peer#637]
Hello. I am making a video call with 'simple-peer' and installed a presenter on the server. I only want to keep the video recordings on the server while I am talking with 'simple-peer'.

what do you think i should do?

https://doc-kurento.readthedocs.io/en/6.9.0/tutorials/js/tutorial-recorder.html

**Comment by nazar-pc** [comment]
Simple-peer is just a library on top of WebRTC implementation in the browser. AFAIK Kurento has an SDK of some kind, so you probably want to use that one instead or figure out how it works and implement it on top of simple-peer.

This is an issue tracker about simple-peer and not Kurento. Since this is not related to simple-peer, I'm closing this issue, but feel free to continue conversation.

**Comment by ahmetozalp** [comment]
I just want to use it to keep video recordings on the server 'kurento'

Is not it possible ?

**Comment by nazar-pc** [comment]
I think it should be, but I do not know much about Kurento.

**Comment by ahmetozalp** [comment]
I found [this](https://github.com/feross/simple-peer/issues/451#issuecomment-477757967) comment
