### ISSUE TITLE
react native: this._pc.addTrack is undefined

### ISSUE THREAD

**Issue by jiangbryn** [feross/simple-peer#647]
Hi,
I got an error when I use simple-peer in react native
![IMG_5CF6CD31EBFB-1](https://user-images.githubusercontent.com/18710673/81314421-b4990f00-904e-11ea-8c9a-f45c95323f0c.jpeg)

I've tried adapter.js but still get this error.
Is there any solution to solve this?

Packages version
"react-native-webrtc": "^1.75.3"
"webrtc-adapter": "^7.5.1"
"simple-peer": "^9.7.0"

**Comment by nazar-pc** [comment]
This means that the WebRTC implementation available to simple-peer is severely out of date and there is nothing simple-peer as a library can or should do in this case. There is a feature request #445 and a few other questions about react-native, but basically all boils down to react-native-webrtc supporting necessary features in the first place.

I believe there is nothing to be done in simple-peer here, so closing, but feel free to continue conversation.

**Comment by TheSalarKhan** [comment]
@jiangbryn  I had the same issue, I wanted to use the clean and convenient interface that simple-peer provides on react-native therefore I created an indirect fork which purely uses addStream and onaddstream instead of the newer addTrack and ontrack.

Link: https://github.com/ExpandoPakistan/simple-peer-legacy

Leaving it here for people who might want to use simple-peer until react-native-webrtc does not add support for addTrack.
