### ISSUE TITLE
Screeching audio sound

### ISSUE THREAD

**Issue by nats12** [feross/simple-peer#675]
Hi, I've implemented a simple react component with video working fine but the audio is off, you hear a screeching sound instead. I've got audio set to true in navigator as seen in docs and I'm using a macbook in which I've allowed access to my mic. Has anyone encountered this before?

I've followed [this](https://github.com/coding-with-chaim/react-video-chat) example primarily if that helps.

Thanks

**Comment by nazar-pc** [comment]
I have never seen this before. Sounds like issue with audio configuration on the machine or CPU load or network limitation, but hard to say for sure.
Simple-peer neither records nor plays audio, so whatever issue is it should not be related to simple-peer.

Closing the issue since there is nothing to be done in simple-peer, but feel free to continue conversation.
