### ISSUE TITLE
Using WebRTC without internet connection and over LAN

### ISSUE THREAD

**Issue by subins2000** [feross/simple-peer#691]
From [reading this](https://stackoverflow.com/a/51877859/1372424), it seems possible to make WebRTC connection through LAN without internet. How can I do this with simple-peer.

I tired the simple HTML example in the README (copy paste offer and answer SDP), but this doesn't work when internet is off. Firefox shows this in console :

```
error DOMException: "Can't create RTCPeerConnections when the network is down"
```
What's the right configuration for simple-peer to do WebRTC connections offline (LAN) ?

My ultimate goal is to make a LAN game in Android. For this, an Android Java signalling server will be created by the host player and all the other players in the network can use this host to make WebRTC connections to each other.

**Comment by nazar-pc** [comment]
First of all, simple-peer is just a wrapper, so "How can I do this with simple-peer" doesn't make a lot of sense since you do it exactly the same way as without it.

Secondly "offline" and "LAN" are 2 completely different things. You, obviously, still need network between 2 machines (which can be LAN, doesn't really matter) in order to connect.

Closing since there is nothing to be done in simple-peer, but feel free to continue conversation.

**Comment by subins2000** [comment]
I meant offline in the sense that no devices in the LAN connection will have access to internet.

I tested it by disconnecting my WiFi, but that meant I had no network, and that's why the browser showed that error message in console. Instead when I tethered my phone and made a LAN with no access to internet, it worked good ! with a signalling server running on my computer. My bad, apologies!
