### ISSUE TITLE
[Question] How to send one stream to several remove clients and from several clients to one merge it ?

### ISSUE THREAD

**Issue by redradist** [feross/simple-peer#706]
Hi all,

I have found this wonderful library and I interested in using it in following scenarios :
1) One client send its stream to several clients in chunks (part by part)
2) Several clients will send data to on client and this client will merge these chunks in one stream and play video

Is it possible to do with this library ?

Seems like I need interpret stream as raw data and slice it on chunks and then send these chunks to other clients which will merge it back ... am I right ?

**Comment by nazar-pc** [comment]
There is no access to raw unencoded stream in WebRTC and simple-peer doesn't do any magic in that regard.
You can send chunks of arbitrary data with data channels though, including when using simple-peer. In fact this is what https://github.com/webtorrent/webtorrent does.

Closing since there is nothing in simple-peer to be done about this, but feel free to continue conversation.
