### ISSUE TITLE
Implementing audio stream is too hard.

### ISSUE THREAD

**Issue by 619** [feross/simple-peer#708]
I'm trying to implement discord like calls. I can successfully establish the websocket connection between the two clients, and I'm probably getting the audio streams as well, but sending it to the other client and playing it is frankly too difficult. Seriously, I have been working on this for two weeks now and I'm not sure I'll ever be able to get it to work. Could you make it possible to implement? I've had an easier and more fun experience writing a compiler.

**Comment by 619** [comment]
Can you please rename some of the functions to be more intuitive like "play" and "send"? Seriously, you can put these functions inside of software for air traffic control towers (signal? wtf?) and nobody would know anything was wrong.

**Comment by nazar-pc** [comment]
Well, first of all, this is a library, rather low level one, not a final product. So ideally you need to understand the topic somewhat in order to make things work the way you need it and numerous apps built with this library prove that it is possible.
Second, API like `play` is not something that makes any sense in context of this library. This library abstracts away work with WebRTC (not WebSocket that you mentioned in the first message) and is only concerned with audio/video tracks and arbitrary data on API level. It doesn't really care where audio/video comes from and how it is used eventually.

The example of sending audio and video is present in readme. If you just copy and paste it it'll work. Reducing that to just audio and extending it to whatever you need is your job, not library authors.

Overall I don't see what can or should be done about this in simple-peer, so closing, but feel free to continue discussion.

**Comment by 619** [comment]
If its a low level library, perhaps you should name it something more accurate like "complicated-peer", or "hard-peer" if you're looking for something shorter. The difficulty I've experienced in implementing this library is unprecedented, and thats certainly not what I was expecting when I installed a package called "simple-peer".

**Comment by nazar-pc** [comment]
If you look at underlying WebRTC API in the browser and number of workarounds for different aspects that simple-peer handles for you, you'll realize that "difficulty .. is unprecedented" is extremely exaggerated to say the least :joy: 

The fact that library doesn't solve the task you need to solve is not library's fault since it wasn't designed for that. It is designed to establish P2P connection and send audio/video/data. As readme shows that is fairly simple to do with a bit of copy-paste.

**Comment by 619** [comment]
1 to 1 Audio chat is precisely what I'm trying to accomplish, and I'm telling you that your copy and paste example does not accomplish it.

From your description it appears that this library was designed to make it easier for developers to implement WebRTC and yet you just said that this library is low level and have objected to the idea that the API should be intuitive, two very contradictory positions. 

Your contempt for your own users is troubling.

**Comment by nazar-pc** [comment]
This library makes low-level things like sending audio/video/data easier. You're free to not use the library if you don't find that is the case for you.
Audio chat is an app, which can use or not use this library.


Since this thread turned from not understanding what library does to straight accusations, I think it is enough.
