### ISSUE TITLE
Can't join to room if initiator already created

### ISSUE THREAD

**Issue by sergeymild** [feross/simple-peer#719]
I cant understand how to join to already create initiator?
i have `new Peer({initiator: true})`
then i trying to connect with `new Peer({initiator: false})`
nothing happens
but if i first create `new Peer({initiator: false})`
and then `new Peer({initiator: true})`
everything works fine

**Comment by jarretttaylor** [comment]
Your Peer object should not be created until you are ready to connect to entities. Specifically, it isn't an object you create and then just have wait around for someone to connect to at some point in the future. Your application needs to handle the process of knowing who wants to connect to whom and then trigger the creation of the respective Peer objects on each side so that they can then begin their negotiation (via signaling).

**Comment by sergeymild** [comment]
ok, i got it, thanks
