### ISSUE TITLE
peer.on('signal') is calling when I add screenShare track when videoCalling is going on 

### ISSUE THREAD

**Issue by Naveena97** [feross/simple-peer#720]
peer.on('signal') is calling again when I addTrack(ex.screenShare track) when a video call is going on and another peer connection is establishing
with error
![Screenshot (197)](https://user-images.githubusercontent.com/60501667/88878870-80e11600-d246-11ea-820e-199b1e6d720e.png)

But the replaceTrack is working fine.I am not able to figure out
Can u please help me in solving these problem. Thanks in advance

**Comment by t-mullen** [comment]
When you use `addTrack` or `addStream`, you are changing details of the connection, so more signalling information needs to be exchanged - so "signal" fires again. This is called "renegotiation".

`replaceTrack` doesn't do this because you're not changing the number of tracks, just replacing one.

This is working as intended, I hope this clears up any confusion.
