### ISSUE TITLE
simplepeer.js is not working on the mobile browser chrome/firefox in android.

### ISSUE THREAD

**Issue by techleadzdevteam** [feross/simple-peer#92]
I am using simplepeer.js with pusher api and I have developed an audio/video calling system but there is a problem that it is not working on the mobile.

 

I have tested my system on Mozilla and chrome on laptop ,it is working fine on both but on the mobile when I call the person ,peer stream starts and then it close suddenly.

 

Can you help me about this issue?

**Comment by feross** [comment]
Do you have any other debug information? Have you checked `chrome://webrtc-internals` to see the status of the WebRTC connections?

My guess is that you'll need to specify a TURN server in order to work on mobile networks. You can learn more here: https://www.html5rocks.com/en/tutorials/webrtc/basics/
